In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
df = pd.read_csv('houseprice.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [15]:
df.shape

(1460, 81)

In [16]:
df['Id'].nunique()

1460

In [17]:
df.drop('Id',axis=1,inplace=True)
df.shape

(1460, 80)

In [18]:
nv = df.isnull().sum()
nv[nv>0]

LotFrontage      259
Alley           1369
MasVnrType         8
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64

In [19]:
df.drop(['PoolQC','Alley','MiscFeature'],axis=1,inplace=True)
nv = df.isnull().sum()
nv[nv>0]

LotFrontage      259
MasVnrType         8
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
Fence           1179
dtype: int64

In [20]:
cat_nan = [i for i in df.columns if df[i].isnull().sum()>0 and df[i].dtypes=='object']
num_nan = [i for i in df.columns if df[i].isnull().sum()>0 and df[i].dtypes!='object']
print(cat_nan)
print(len(cat_nan))
print(num_nan)
print(len(num_nan))

['MasVnrType', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'Fence']
13
['LotFrontage', 'MasVnrArea', 'GarageYrBlt']
3

#### Basement null value Handling

In [21]:
bs_cols = ['BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2']
for i in bs_cols:
    df[i].fillna('No_Base',inplace=True)
nv = df.isnull().sum()
nv[nv>0]

LotFrontage      259
MasVnrType         8
MasVnrArea         8
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
Fence           1179
dtype: int64

In [22]:
gar_cols = ['GarageType', 'GarageFinish', 'GarageQual', 'GarageCond']
for i in gar_cols:
    df[i].fillna('No_Garage',inplace=True)
nv = df.isnull().sum()
nv[nv>0]

LotFrontage     259
MasVnrType        8
MasVnrArea        8
Electrical        1
FireplaceQu     690
GarageYrBlt      81
Fence          1179
dtype: int64

In [25]:
for i in ['LotFrontage','MasVnrArea']:
    df[i].fillna(df[i].mean(),inplace=True)
nv = df.isnull().sum()
nv[nv>0]

MasVnrType        8
Electrical        1
FireplaceQu     690
GarageYrBlt      81
Fence          1179
dtype: int64

In [29]:
nv = df.isnull().sum()
nv[nv>0]

MasVnrType        8
Electrical        1
FireplaceQu     690
GarageYrBlt      81
Fence          1179
dtype: int64

In [34]:
for i in nv[nv>0].index:
    print(df[i].value_counts())

None       864
BrkFace    445
Stone      128
BrkCmn      15
Name: MasVnrType, dtype: int64
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: Electrical, dtype: int64
Gd    380
TA    313
Fa     33
Ex     24
Po     20
Name: FireplaceQu, dtype: int64
2005.0    65
2006.0    59
2004.0    53
2003.0    50
2007.0    49
          ..
1906.0     1
1908.0     1
1933.0     1
1900.0     1
1927.0     1
Name: GarageYrBlt, Length: 97, dtype: int64
MnPrv    157
GdPrv     59
GdWo      54
MnWw      11
Name: Fence, dtype: int64

In [35]:
nv[nv>0].index

Index(['MasVnrType', 'Electrical', 'FireplaceQu', 'GarageYrBlt', 'Fence'], dtype='object')

In [36]:
for i in ['MasVnrType', 'Electrical', 'FireplaceQu', 'Fence']:
    x = df[i].mode().max()
    df[i].fillna(x,inplace=True)

In [37]:
nv = df.isnull().sum()
nv[nv>0]

GarageYrBlt    81
dtype: int64

In [38]:
df['GarageYrBlt'].fillna(2005.0,inplace=True)
nv = df.isnull().sum()
nv[nv>0]

Series([], dtype: int64)

In [39]:
df.shape

(1460, 77)

### Outlier Handling

In [40]:
df.describe(percentiles=[0.97,0.98,0.99]).T

,count,mean,std,min,50%,97%,98%,99%,max
MSSubClass,1460.0,56.897260,42.300571,20.0,50.000000,160.00,188.20,190.00,190.0
LotFrontage,1460.0,70.049958,22.024023,21.0,70.049958,114.00,120.82,137.41,313.0
LotArea,1460.0,10516.828082,9981.264932,1300.0,9478.500000,21571.80,25251.62,37567.64,215245.0
OverallQual,1460.0,6.099315,1.382997,1.0,6.000000,9.00,9.00,10.00,10.0
OverallCond,1460.0,5.575342,1.112799,1.0,5.000000,8.00,8.00,9.00,9.0
YearBuilt,1460.0,1971.267808,30.202904,1872.0,1973.000000,2007.00,2008.00,2009.00,2010.0
YearRemodAdd,1460.0,1984.865753,20.645407,1950.0,1994.000000,2008.00,2008.00,2009.00,2010.0
MasVnrArea,1460.0,103.685262,180.569112,0.0,0.000000,573.69,650.82,791.28,1600.0
BsmtFinSF1,1460.0,443.639726,456.098091,0.0,383.500000,1375.99,1442.64,1572.41,5644.0
BsmtFinSF2,1460.0,46.549315,161.319273,0.0,0.000000,546.23,658.12,830.38,1474.0
BsmtUnfSF,1460.0,567.240411,441.866955,0.0,477.500000,1589.38,1678.20,1797.05,2336.0
TotalBsmtSF,1460.0,1057.429452,438.705324,0.0,991.500000,1905.46,2001.64,2155.05,6110.0
1stFlrSF,1460.0,1162.626712,386.587738,334.0,1087.000000,1981.61,2072.28,2219.46,4692.0
2ndFlrSF,1460.0,346.992466,436.528436,0.0,0.000000,1245.53,1318.56,1418.92,2065.0
LowQualFinSF,1460.0,5.844521,48.623081,0.0,0.000000,0.00,0.00,360.00,572.0
GrLivArea,1460.0,1515.463699,525.480383,334.0,1464.000000,2633.23,2782.38,3123.48,5642.0
BsmtFullBath,1460.0,0.425342,0.518911,0.0,0.000000,1.00,1.00,2.00,3.0
BsmtHalfBath,1460.0,0.057534,0.238753,0.0,0.000000,1.00,1.00,1.00,2.0
FullBath,1460.0,1.565068,0.550916,0.0,2.000000,2.00,3.00,3.00,3.0
HalfBath,1460.0,0.382877,0.502885,0.0,0.000000,1.00,1.00,1.00,2.0
BedroomAbvGr,1460.0,2.866438,0.815778,0.0,3.000000,4.00,4.00,5.00,8.0
KitchenAbvGr,1460.0,1.046575,0.220338,0.0,1.000000,2.00,2.00,2.00,3.0
TotRmsAbvGrd,1460.0,6.517808,1.625393,2.0,6.000000,10.00,10.82,11.00,14.0
Fireplaces,1460.0,0.613014,0.644666,0.0,1.000000,2.00,2.00,2.00,3.0
GarageYrBlt,1460.0,1979.976027,24.749688,1900.0,1984.500000,2008.00,2008.00,2009.00,2010.0
GarageCars,1460.0,1.767123,0.747315,0.0,2.000000,3.00,3.00,3.00,4.0
GarageArea,1460.0,472.980137,213.804841,0.0,480.000000,884.00,907.46,1002.79,1418.0
WoodDeckSF,1460.0,94.244521,125.338794,0.0,0.000000,385.38,430.10,505.46,857.0
OpenPorchSF,1460.0,46.660274,66.256028,0.0,25.000000,213.23,240.82,285.82,547.0
EnclosedPorch,1460.0,21.954110,61.119149,0.0,0.000000,216.00,235.64,261.05,552.0
3SsnPorch,1460.0,3.409589,29.317331,0.0,0.000000,0.00,0.00,168.00,508.0
ScreenPorch,1460.0,15.060959,55.757415,0.0,0.000000,192.00,223.64,268.05,480.0
PoolArea,1460.0,2.758904,40.177307,0.0,0.000000,0.00,0.00,0.00,738.0
MiscVal,1460.0,43.489041,496.123024,0.0,0.000000,400.00,500.00,700.00,15500.0
MoSold,1460.0,6.321918,2.703626,1.0,6.000000,12.00,12.00,12.00,12.0
YrSold,1460.0,2007.815753,1.328095,2006.0,2008.000000,2010.00,2010.00,2010.00,2010.0
SalePrice,1460.0,180921.195890,79442.502883,34900.0,163000.000000,374230.00,394931.06,442567.01,755000.0

In [41]:
df.describe(percentiles=[0.97,0.98,0.99]).T.index

Index(['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces',
       'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold', 'SalePrice'],
      dtype='object')

In [42]:
out_cols_98 = ['LotFrontage','LotArea','MasVnrArea','BsmtFinSF1','BsmtFinSF2',
               'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
              'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'HalfBath',
              'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces',
               'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
              'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
               'SalePrice']
print(out_cols_98)

['LotFrontage', 'LotArea', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'SalePrice']

In [45]:
def oh1(x):
    x = x.clip(upper=x.quantile(0.98))
    return x

In [46]:
df[out_cols_98] = df[out_cols_98].apply(oh1)

In [47]:
df.describe(percentiles=[0.01,0.02,0.03,0.05]).T

,count,mean,std,min,1%,2%,3%,5%,50%,max
MSSubClass,1460.0,56.897260,42.300571,20.0,20.00,20.00,20.00,20.00,50.000000,190.00
LotFrontage,1460.0,69.405164,18.845067,21.0,21.00,24.00,30.00,35.95,70.049958,120.82
LotArea,1460.0,9884.318219,4269.103743,1300.0,1680.00,2124.74,2522.00,3311.70,9478.500000,25251.62
OverallQual,1460.0,6.099315,1.382997,1.0,3.00,4.00,4.00,4.00,6.000000,10.00
OverallCond,1460.0,5.575342,1.112799,1.0,3.00,3.00,4.00,4.00,5.000000,9.00
YearBuilt,1460.0,1971.267808,30.202904,1872.0,1899.18,1908.36,1910.00,1916.00,1973.000000,2010.00
YearRemodAdd,1460.0,1984.865753,20.645407,1950.0,1950.00,1950.00,1950.00,1950.00,1994.000000,2010.00
MasVnrArea,1460.0,99.054851,159.552455,0.0,0.00,0.00,0.00,0.00,0.000000,650.82
BsmtFinSF1,1460.0,436.678219,424.424497,0.0,0.00,0.00,0.00,0.00,383.500000,1442.64
BsmtFinSF2,1460.0,41.938082,136.258146,0.0,0.00,0.00,0.00,0.00,0.000000,658.12
BsmtUnfSF,1460.0,563.631507,431.331047,0.0,0.00,0.00,0.00,0.00,477.500000,1678.20
TotalBsmtSF,1460.0,1048.256986,398.396991,0.0,0.00,0.00,312.33,519.30,991.500000,2001.64
1stFlrSF,1460.0,1155.655068,358.974939,334.0,520.00,583.70,625.00,672.95,1087.000000,2072.28
2ndFlrSF,1460.0,343.673151,427.613429,0.0,0.00,0.00,0.00,0.00,0.000000,1318.56
LowQualFinSF,1460.0,0.000000,0.000000,0.0,0.00,0.00,0.00,0.00,0.000000,0.00
GrLivArea,1460.0,1504.468767,483.292715,334.0,692.18,768.00,796.00,848.00,1464.000000,2782.38
BsmtFullBath,1460.0,0.413699,0.492665,0.0,0.00,0.00,0.00,0.00,0.000000,1.00
BsmtHalfBath,1460.0,0.056164,0.230318,0.0,0.00,0.00,0.00,0.00,0.000000,1.00
FullBath,1460.0,1.565068,0.550916,0.0,1.00,1.00,1.00,1.00,2.000000,3.00
HalfBath,1460.0,0.374658,0.484200,0.0,0.00,0.00,0.00,0.00,0.000000,1.00
BedroomAbvGr,1460.0,2.839726,0.748082,0.0,1.00,1.00,1.00,2.00,3.000000,4.00
KitchenAbvGr,1460.0,1.045205,0.211098,0.0,1.00,1.00,1.00,1.00,1.000000,2.00
TotRmsAbvGrd,1460.0,6.504521,1.584136,2.0,3.00,4.00,4.00,4.00,6.000000,10.82
Fireplaces,1460.0,0.609589,0.634547,0.0,0.00,0.00,0.00,0.00,1.000000,2.00
GarageYrBlt,1460.0,1979.976027,24.749688,1900.0,1917.18,1920.00,1924.00,1930.00,1984.500000,2010.00
GarageCars,1460.0,1.763699,0.739318,0.0,0.00,0.00,0.00,0.00,2.000000,3.00
GarageArea,1460.0,470.137534,205.938812,0.0,0.00,0.00,0.00,0.00,480.000000,907.46
WoodDeckSF,1460.0,92.019178,117.263208,0.0,0.00,0.00,0.00,0.00,0.000000,430.10
OpenPorchSF,1460.0,45.170959,59.666175,0.0,0.00,0.00,0.00,0.00,25.000000,240.82
EnclosedPorch,1460.0,21.067260,56.943392,0.0,0.00,0.00,0.00,0.00,0.000000,235.64
3SsnPorch,1460.0,0.000000,0.000000,0.0,0.00,0.00,0.00,0.00,0.000000,0.00
ScreenPorch,1460.0,13.677534,48.367922,0.0,0.00,0.00,0.00,0.00,0.000000,223.64
PoolArea,1460.0,0.000000,0.000000,0.0,0.00,0.00,0.00,0.00,0.000000,0.00
MiscVal,1460.0,16.482192,86.867615,0.0,0.00,0.00,0.00,0.00,0.000000,500.00
MoSold,1460.0,6.321918,2.703626,1.0,1.00,1.00,1.00,2.00,6.000000,12.00
YrSold,1460.0,2007.815753,1.328095,2006.0,2006.00,2006.00,2006.00,2006.00,2008.000000,2010.00
SalePrice,1460.0,179093.495753,71929.291417,34900.0,61815.97,79000.00,82000.00,88000.00,163000.000000,394931.06

In [52]:
out_cols_01 = ['LotArea', 'OverallQual', 'OverallCond','1stFlrSF','TotRmsAbvGrd',
                'GrLivArea','SalePrice']
print(out_cols_01)

['LotArea', 'OverallQual', 'OverallCond', '1stFlrSF', 'TotRmsAbvGrd', 'GrLivArea', 'SalePrice']

In [53]:
def oh2(x):
    x = x.clip(lower=x.quantile(0.01))
    return x

In [54]:
df[out_cols_01] = df[out_cols_01].apply(oh2)

In [55]:
df.shape

(1460, 77)

### Get_Dummies

In [56]:
cat_cols = [i for i in df.columns if df[i].dtypes=='object']
print(len(cat_cols))
print(cat_cols)

40
['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'Fence', 'SaleType', 'SaleCondition']

In [57]:
df1 = pd.get_dummies(data=df,columns=cat_cols,drop_first=True)
df1.shape

(1460, 249)

In [62]:
x = df1.drop('SalePrice',axis=1)
y = df1['SalePrice']
print(x.shape)
print(y.shape)

(1460, 248)
(1460,)

In [63]:
from sklearn.preprocessing import StandardScaler

In [64]:
sc = StandardScaler()
x_sc = sc.fit_transform(x)
x_sc.shape

(1460, 248)

### PCA from skelarn

In [65]:
from sklearn.decomposition import PCA

In [68]:
pca1 = PCA()
pc1 = pca1.fit_transform(x_sc)
print(pc1.shape)

(1460, 248)

In [71]:
eig_val1 = pd.DataFrame({'Var':pca1.explained_variance_})
eig_val1.head()

         Var
0  16.889245
1   8.089807
2   7.198392
3   5.890462
4   5.542149

In [74]:
eig_val1['Contri'] = eig_val1['Var']*100/eig_val1['Var'].sum()
eig_val1.head()

         Var    Contri
0  16.889245  6.888848
1   8.089807  3.299700
2   7.198392  2.936107
3   5.890462  2.402624
4   5.542149  2.260552

In [75]:
eig_val1['CumSum'] = eig_val1['Contri'].cumsum()
eig_val1.tail()

              Var        Contri  CumSum
243  6.048291e-32  2.466999e-32   100.0
244  6.048291e-32  2.466999e-32   100.0
245  6.048291e-32  2.466999e-32   100.0
246  4.627411e-32  1.887445e-32   100.0
247  2.643455e-32  1.078222e-32   100.0

In [76]:
eig_val1[eig_val1['CumSum']<76].tail()

         Var    Contri     CumSum
83  1.019021  0.415642  74.251955
84  1.009164  0.411621  74.663576
85  1.002222  0.408790  75.072366
86  0.993842  0.405372  75.477738
87  0.978277  0.399023  75.876761

In [77]:
res_df = pd.DataFrame(pc1)
res_df.head()

,0,1,2,3,4,5,6,7,8,9,...,238,239,240,241,242,243,244,245,246,247
0,-4.464266,1.864573,-0.442591,-0.198390,-1.442747,-2.064312,-0.583703,-1.332883,1.683657,-0.987843,...,0.001264,1.746938e-15,-3.833133e-16,-2.503281e-16,2.785685e-16,9.759917e-17,3.225347e-16,-3.264428e-17,3.698753e-17,8.533404e-17
1,-0.102440,-3.101643,0.375792,-1.028276,0.580757,-0.839022,0.912768,-1.174784,-0.263074,-0.199181,...,0.043600,-2.176509e-17,1.673960e-16,9.943667e-17,-8.860665e-17,-2.611317e-16,-2.570838e-16,2.892276e-16,2.017975e-16,-1.567469e-16
2,-5.152943,1.075597,0.064882,0.333054,-0.703609,-2.513562,0.007636,-1.981288,1.815666,-0.791633,...,-0.013865,-1.432877e-15,1.341544e-16,-2.517090e-16,-1.893685e-16,-3.979395e-17,-9.825584e-17,2.534489e-17,8.476779e-17,6.272710e-17
3,1.317366,0.372536,-0.794489,2.993878,-0.539634,0.981081,0.865942,-0.852970,-0.922942,-1.604405,...,0.003966,-6.209334e-16,2.965726e-16,5.047826e-16,-1.318774e-16,7.755787e-17,-1.530063e-16,-7.167035e-17,9.579173e-19,-2.465010e-16
4,-6.891859,0.377635,0.802507,2.566966,0.745329,-3.065300,-0.449504,-0.834175,2.748574,-0.930788,...,-0.003807,1.050813e-15,-2.513606e-16,-4.058885e-16,-2.831473e-16,-2.128887e-16,5.784383e-16,-2.143634e-16,-2.689726e-16,2.418104e-16

In [80]:
x_reg = res_df.iloc[:,:86]

y_reg = y
print(x_reg.shape)
print(y_reg.shape)

(1460, 86)
(1460,)

In [81]:
from sklearn.model_selection import train_test_split
x_train1,x_test1,y_train1,y_test1 = train_test_split(x_reg,y_reg,test_size=0.25)
print(x_train1.shape)
print(x_test1.shape)
print(y_train1.shape)
print(y_test1.shape)

(1095, 86)
(365, 86)
(1095,)
(365,)

In [83]:
from sklearn.linear_model import LinearRegression

In [84]:
m1 = LinearRegression()
m1.fit(x_train1,y_train1)
print('Training_score',m1.score(x_train1,y_train1))
print('Testing_score',m1.score(x_test1,y_test1))

Training_score 0.8874792635641522
Testing_score 0.8413379710739936

In [86]:
ypred = m1.predict(x_test1)

In [ ]:
# MSE,MAE,RMSE, R2_score